
// const messages = {
//     EMAIL_NOT_FOUND : "Email not found",
//     WRONG_CREDENTIALS_ENTERED: "Incorrect email or password!",
//     INTERNAL_SERVER_ERROR: "Internal Server Error",
//     USER_NOT_FOUND: "User not found",
//     PASSWORD_RESET_LINK_SENT_SUCCESSFULLY: "Password reset link sent successfully",
//     INVALID_EXPIRED_LINK: "Invalid or expired link",
//     PASSWORD_CONFIRM_PASSWORD_NOT_MATCH: "Password and Confirm Password do not match",
//     PASSWORD_RESET_SUCCESS: "Password reset successful",
//     NEWS_CREATED_SUCCESS: "News created successfully",
//     NO_NEWS_FOUND: "No news found for type:",
//     NO_NEWS_FOUND_WITH_ID: "No news found with id:",
//     NEWS_UPDATED_SUCCESS: "News updated successfully",
//     NEWS_DELETED_SUCCESS: "News deleted successfully",
//     FAQ_CREATED_SUCCESS: "FAQ created successfully",
//     NO_FAQ_FOUND_FOR_TYPE: "No FAQ found for type:",
//     NO_FAQ_FOUND_WITH_ID: "No FAQ found with id:",
//     FAQ_DELETED_SUCCESS: "FAQ deleted successfully",
//     FAQ_UPDATED_SUCCESS: "FAQ updated successfully",
//     CONTACT_CREATED_SUCCESS: "Contact created successfully",
//     CONTACT_UPDATED_SUCCESS: "Contact Updated Successfully",
//     CONTACT_NOT_FOUND: "Contact not found",
//     CONTACT_DELETED_SUCCESS: "Contact deleted successfully",
//     FAVORITE_CREATED_SUCCESS: "Favourite created successfully",
//     FAVORITE_NOT_FOUND: "Favourite not found",
//     FAVORITE_UPDATED_SUCCESS: "Favourite Updated successfully",
//     FAVORITE_DELETED_SUCCESS: "Favourite Deleted successfully",
//     DEALER_CONTACT_FORM_SUBMIT: "Dealer contact form submitted successfully",
//     LOGIN_SUCCESS: "Login successfully!",
//     ADMINFOUND: "Admin found Successfully",
//     USER_UPDATED_SUCCESSFULLY: "User Updated Successfully",
//     CHART_CREATED_SUCCESS: "Chart created Successfully",
//     NO_CHARTS_FOUND: "No chart Found",
//     NO_CHART_FOUND_WITH_ID:"No Chart found with id:",
//     CHART_UPDATED_SUCCESS:"Chart Updated Successfully",
//     CHART_DELETED_SUCCESS:"Chart Deleted Successfully",
//     BRAND_UPDATED_SUCCESSFULLY: "Brand logo added successfully",
//     BRANDS_WITH_LOGO: "Here is your brand logo list",
//     NO_IMAGE_FILE_FOR_BRAND_PROVIDED: "No image file is provided",




//     ////////////////////////////////////////////  NOT IN USE
//     ACCOUNT_CREATED : "Account created successfully!",
//     ACCOUNT_CREATION_FAILED: "Account creation failed!",
//     ACCOUNT_ALREADY_EXISTS: "Account already exists!",
    
 
   
// }
 
// module.exports = messages;

const messages = {
    // English messages
    19: {
        EMAIL_NOT_FOUND : "Email not found",
        WRONG_CREDENTIALS_ENTERED: "Incorrect email or password!",
        INTERNAL_SERVER_ERROR: "Internal Server Error",
        USER_NOT_FOUND: "User not found",
        PASSWORD_RESET_LINK_SENT_SUCCESSFULLY: "Password reset link sent successfully",
        INVALID_EXPIRED_LINK: "Invalid or expired link",
        PASSWORD_CONFIRM_PASSWORD_NOT_MATCH: "Password and Confirm Password do not match",
        PASSWORD_RESET_SUCCESS: "Password reset successful",
        NEWS_CREATED_SUCCESS: "News created successfully",
        NO_NEWS_FOUND: "No news found for type:",
        NO_NEWS_FOUND_WITH_ID: "No news found with id:",
        NEWS_UPDATED_SUCCESS: "News updated successfully",
        NEWS_DELETED_SUCCESS: "News deleted successfully",
        FAQ_CREATED_SUCCESS: "FAQ created successfully",
        NO_FAQ_FOUND_FOR_TYPE: "No FAQ found for type:",
        NO_FAQ_FOUND_WITH_ID: "No FAQ found with id:",
        FAQ_DELETED_SUCCESS: "FAQ deleted successfully",
        FAQ_UPDATED_SUCCESS: "FAQ updated successfully",
        CONTACT_CREATED_SUCCESS: "Contact created successfully",
        CONTACT_UPDATED_SUCCESS: "Contact Updated Successfully",
        CONTACT_NOT_FOUND: "Contact not found",
        CONTACT_DELETED_SUCCESS: "Contact deleted successfully",
        FAVORITE_CREATED_SUCCESS: "Favourite created successfully",
        MAX_LEVEL_CREATION: "Maximum 5 favorites can be saved",
        FAVORITE_NOT_FOUND: "Favourite not found",
        FAVORITE_UPDATED_SUCCESS: "Favourite Updated successfully",
        FAVORITE_DELETED_SUCCESS: "Favourite Deleted successfully",
        DEALER_CONTACT_FORM_SUBMIT: "Dealer contact form submitted successfully",
        LOGIN_SUCCESS: "Login successfully!",
        ADMINFOUND: "Admin found Successfully",
        USER_UPDATED_SUCCESSFULLY: "User Updated Successfully",
        CHART_CREATED_SUCCESS: "Chart created Successfully",
        NO_CHARTS_FOUND: "No chart Found",
        NO_CHART_FOUND_WITH_ID:"No Chart found with id:",
        CHART_UPDATED_SUCCESS:"Chart Updated Successfully",
        CHART_DELETED_SUCCESS:"Chart Deleted Successfully",
        BRAND_UPDATED_SUCCESSFULLY: "Brand logo added successfully",
        BRANDS_WITH_LOGO: "Here is your brand logo list",
        NO_IMAGE_FILE_FOR_BRAND_PROVIDED: "No image file is provided",
        VEHICLE_ID_AND_Language_ID_ERROR: "Vehicle ID and Language ID are required in the query parameter",
        OPTIONS_RETRIEVED_SUCCESS: "Colour options  retrieved successfully",
        MAX_LEVEL_CREATION_CHARTS: "Maximum 10 records can be created in Charts",
        VERSION_SAVED_SUCCESS: "Selected version saved successfully",
        FAVOURITE_SAVED_SUCCESS: "Favorite saved successfully",
        CAR_TRIM_RETRIEVED: 'Car Trim Levels retrieved successfully',
        CAR_FUEL_RETRIEVED:'Car fuel types retrieved successfully',
        BODY_TYPES_RETRIEVED: 'Body Types retrieved successfully',
        CAR_PRICE_RETRIEVED :"Car price range retrieved successfully",
        CHART_FETCHED_SUCCESS: "all charts for position fetched successfully",
        INVALID_FORMAT: "Invalid Format",
        DUPLICATE_ID_AND_FORMAT:"Duplicate ID found in the updates",
        DUPLICATE_POSITION_FOUND:"Duplicate position found in the updates",
        CAR_PRICE_RANGE:"Car price range retrieved successfully",
        ID_POSITION_REQUIRED:"ID and position are required",
        BULK_UPDATE_CHART_POSITION:"Bulk update of chart positions successful",
        NO_DATA:"No Data",
        BODY_TYPE_RETRIEVED_SUCCESS:"Body types retrieved successfully",
        CAR_FUEL_TYPE_RETRIEVED_SUCCESS:"Car fuel types retrieved successfully",
        MISSING_FIELD:"Some Fields are missing",
        CAR_TRIM_LEVEL_SUCCESS:"Car Trim Levels retrieved successfully",
        LANGUAGE_SETTINGS_CREATED_SUCCESS:"Language Created Successfully",
        LANGUAGE_SETTINGS_RETRIEVED_SUCCESS:"Language Retrieved Successfully",
        SETTINGS_NOT_FOUND:"Setting Not Found",
        LANGUAGE_SETTINGS_UPDATED_SUCCESS:"Language Setting Updated Successfully",
        LANGUAGE_SETTING_DELETED:"Language Setting Deleted Successfully",
        NO_RECORD_SETTING_FOUND:"No Record of Setting Found",
        CHART_CATEGORY_NAME_NOT_FOUND:"Chart Category Name not Found",
        NO_CHARTS_NAME_PROVIDED:"No charts Name Provided",
        CONTACT_AND_DEAL_CREATED_SUCCESSFULLY:"Contact, Deal, and File uploaded successfully",
        SCHEDULE_SET_SUCCESS:"Schedule for ftp Updated",
        DB_CHOICE_REQUIRED:"DB_CHOICE_REQUIRED",
        FORCE_UPDATE_SUCCESS:"FORCE_UPDATE_SUCCESS",
        EXTRACT_PATH_REQUIRED:"EXTRACT_PATH_REQUIRED",
        MANUAL_UPDATE_SUCCESS:"MANUAL_UPDATE_SUCCESS",
        NO_INACTIVE_DB:"NO_INACTIVE_DB"
    },

    // Danish messages
    24: {
            EMAIL_NOT_FOUND : "E-mail ikke fundet",
            WRONG_CREDENTIALS_ENTERED: "Forkert e-mail eller adgangskode!",
            INTERNAL_SERVER_ERROR: "Intern Serverfejl",
            USER_NOT_FOUND: "Bruger ikke fundet",
            PASSWORD_RESET_LINK_SENT_SUCCESSFULLY: "Nulstil adgangskodelink sendt med succes",
            INVALID_EXPIRED_LINK: "Ugyldig eller udløbet link",
            PASSWORD_CONFIRM_PASSWORD_NOT_MATCH: "Adgangskode og Bekræft adgangskode matcher ikke",
            PASSWORD_RESET_SUCCESS: "Nulstil adgangskode succesfuld",
            NEWS_CREATED_SUCCESS: "Nyheder oprettet med succes",
            NO_NEWS_FOUND: "Ingen nyheder fundet for type:",
            NO_NEWS_FOUND_WITH_ID: "Ingen nyheder fundet med id:",
            NEWS_UPDATED_SUCCESS: "Nyheder opdateret med succes",
            NEWS_DELETED_SUCCESS: "Nyheder slettet med succes",
            FAQ_CREATED_SUCCESS: "FAQ oprettet med succes",
            NO_FAQ_FOUND_FOR_TYPE: "Ingen FAQ fundet for type:",
            NO_FAQ_FOUND_WITH_ID: "Ingen FAQ fundet med id:",
            FAQ_DELETED_SUCCESS: "FAQ slettet med succes",
            FAQ_UPDATED_SUCCESS: "FAQ opdateret med succes",
            CONTACT_CREATED_SUCCESS: "Kontakt oprettet med succes",
            CONTACT_UPDATED_SUCCESS: "Kontakt opdateret med succes",
            CONTACT_NOT_FOUND: "Kontakt ikke fundet",
            CONTACT_DELETED_SUCCESS: "Kontakt slettet med succes",
            FAVORITE_CREATED_SUCCESS: "Favorit oprettet med succes",
            MAX_LEVEL_CREATION: "Højst 5 favoritter kan gemmes",
            FAVORITE_NOT_FOUND: "Favorit ikke fundet",
            FAVORITE_UPDATED_SUCCESS: "Favorit opdateret med succes",
            FAVORITE_DELETED_SUCCESS: "Favorit slettet med succes",
            DEALER_CONTACT_FORM_SUBMIT: "Forhandler kontaktformular indsendt med succes",
            LOGIN_SUCCESS: "Login med succes!",
            ADMINFOUND: "Admin fundet med succes",
            USER_UPDATED_SUCCESSFULLY: "Bruger opdateret med succes",
            CHART_CREATED_SUCCESS: "Diagram oprettet med succes",
            NO_CHARTS_FOUND: "Ingen diagrammer fundet",
            NO_CHART_FOUND_WITH_ID:"Ingen diagram fundet med id:",
            CHART_UPDATED_SUCCESS:"Diagram opdateret med succes",
            CHART_DELETED_SUCCESS:"Diagram slettet med succes",
            BRAND_UPDATED_SUCCESSFULLY: "Brandlogo tilføjet med succes",
            BRANDS_WITH_LOGO: "Her er din liste over brandlogoer",
            NO_IMAGE_FILE_FOR_BRAND_PROVIDED: "Ingen billedfil er angivet for brand",
            VEHICLE_ID_AND_Language_ID_ERROR: "Køretøjs-ID og Sprog-ID er påkrævet i forespørgselsparametret",
            OPTIONS_RETRIEVED_SUCCESS: "Farvevalg hentet med succes",
            CAR_PRICE_RANGE:"Bilprisinterval blev hentet succesfuldt",
            MAX_LEVEL_CREATION_CHARTS: "Højst 10 poster kan oprettes i diagrammer",
            VERSION_SAVED_SUCCESS: "Valgt version gemt med succes",
            FAVOURITE_SAVED_SUCCESS: "Favorit gemt succesfuldt",
            CAR_TRIM_RETRIEVED: 'Bil trimniveauer hentet med succes',
            CAR_FUEL_RETRIEVED:'Bilbrændstoftyper hentet med succes',
            BODY_TYPES_RETRIEVED: 'Kropstyper hentet med succes',
            CAR_PRICE_RETRIEVED :"Bilprisinterval hentet med succes",
            CHART_FETCHED_SUCCESS :"Alle diagrammer for position blev hentet succesfuldt",
            INVALID_FORMAT: "Ugyldigt format",
            DUPLICATE_ID_AND_FORMAT:"Dobbelt ID fundet i opdateringerne",
            DUPLICATE_POSITION_FOUND:"Dobbelt position fundet i opdateringerne",
            ID_POSITION_REQUIRED:"ID og position er påkrævet",
            BULK_UPDATE_CHART_POSITION:"Stor opdatering af diagrampositioner vellykket",
            NO_DATA:"Ingen data",
            BODY_TYPE_RETRIEVED_SUCCESS:"Kropstyper blev hentet succesfuldt",
            CAR_FUEL_TYPE_RETRIEVED_SUCCESS:"Bilbrændstoftyper blev hentet succesfuldt",
            MISSING_FIELD:"Nogle felter mangler",
            CAR_TRIM_LEVEL_SUCCESS:"Biltrimniveauer blev hentet succesfuldt",
            LANGUAGE_SETTINGS_CREATED_SUCCESS:"Sprog oprettet succesfuld",
            LANGUAGE_SETTINGS_RETRIEVED_SUCCESS:"Sprog hentet succesfuldt",
            SETTINGS_NOT_FOUND:"Indstilling ikke fundet",
            LANGUAGE_SETTINGS_UPDATED_SUCCESS:"Sprogindstillingen blev opdateret succesfuldt",
            LANGUAGE_SETTING_DELETED:"Sprogindstillingen er blevet slettet succesfuldt",
            NO_RECORD_SETTING_FOUND:"Ingen indstilling fundet",
            CHART_CATEGORY_NAME_NOT_FOUND:"Diagramkategoriens navn blev ikke fundet",
            NO_CHARTS_NAME_PROVIDED:"Ingen diagramnavn angivet",
            CONTACT_AND_DEAL_CREATED_SUCCESSFULLY:"Succesfuld indsendelse af forespørgsel",
            CONTACT_CREATED_WITH_EMAIL_ONLY:"Vi sender din konfiguration på mail",
            SCHEDULE_SET_SUCCESS:"Schedule for ftp Updated",
            DB_CHOICE_REQUIRED:"DB_CHOICE_REQUIRED",
            FORCE_UPDATE_SUCCESS:"FORCE_UPDATE_SUCCESS",
            EXTRACT_PATH_REQUIRED:"EXTRACT_PATH_REQUIRED",
            MANUAL_UPDATE_SUCCESS:"MANUAL_UPDATE_SUCCESS",
            NO_INACTIVE_DB:"NO_INACTIVE_DB"
    }
};

export default messages;